kind: Pod
apiVersion: v1
metadata:
  name: exercise-app
  labels:
    app: exercise
spec:
  containers:
  - name: exercise-app
    image: exercise-app
    args:
    - "-text=exercise"
---
kind: Service
apiVersion: v1
metadata:
  name: exercise-service
spec:
  selector:
    app: exercise
  ports:
  # Default port used by the image
  - port: 5000