apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exercise-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: exercise-service
            port:
              number: 5000